apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "kiss-eck.name" . }}
  labels:
  {{- include "kiss-eck.labels" . | nindent 4 }}
spec:
  nodeSets:
  - config:
      node.roles:
      - data
      - ingest
      - master
      node.store.allow_mmap: false
    count: {{ .Values.elasticsearchCount }}
    name: default
    podTemplate:
      spec:
        {{- with .Values.resources }}
        containers:
        - name: elasticsearch
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- if .Values.persistence.enabled }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClassName }}
    {{- end }}
  version: {{ .Values.elasticVersion }}  
